In [21]:
import pandas as pd
import numpy as np

In [22]:
d_mov = pd.read_csv('m3a/Y_Movement.csv')
d_mov

File Name        Date  YT3  YT7  \
0                 A_ArchrockInc_ArchrockPartnersLP.pdf    1/2/2018    0    1   
1     A_CommercialMetalsCo_USRebarAssetsFromGerdau.pdf    1/2/2018    1    1   
2                    M_DominionEnergyInc_SCANACorp.pdf    1/3/2018    1    0   
3    A_Noble EnergyIncsInterestInCONEMidstreamPartn...    1/4/2018    0    0   
4                            A_VIPPetcare_PetIQInc.pdf    1/8/2018    1    1   
..                                                 ...         ...  ...  ...   
811                     A_ZyngaInc_SmallGiantGames.pdf  12/20/2018    1    1   
812  A_ArrisInternationalPLC_RuckusWireless&ICXSwit...  12/14/2017    0    0   
813                             A_CraneCo_Crane&Co.pdf   12/6/2017    0    0   
814  A_GoldenEntertainment_AmericanCasino&Entertain...   6/12/2017    1    1   
815                   A_Deere&Company_WirtgenGroup.pdf    6/1/2017    1    1   

     YT15  
0       1  
1       1  
2       0  
3       0  
4       1  
..    ...  
811     1  
812     0  
813     1  
814     1  
815     0  

[816 rows x 5 columns]

In [26]:
train_idx = pd.read_csv('m3a/Train_index.csv')
train_idx = train_idx['index'].to_numpy()
test_idx = pd.read_csv('m3a/Test_index.csv')
test_idx = test_idx['index'].to_numpy()

In [29]:
df_train = d_mov.iloc[train_idx]
df_test = d_mov.iloc[test_idx]

In [31]:
print(np.unique(df_train['YT3'], return_counts=True))
print(np.unique(df_test['YT3'], return_counts=True))

(array([0, 1], dtype=int64), array([314, 383], dtype=int64))
(array([0, 1], dtype=int64), array([63, 56], dtype=int64))


In [33]:
print(63 / (63 + 56))
print(314 / (314 + 383))

0.5294117647058824
0.45050215208034433


In [ ]:
print(Y_Train)

In [16]:
recs = []
for i in range(1, 6):
    recs.append([i, f's{i}', 0.1*i])

In [17]:
d1 = pd.DataFrame(recs, columns=['c1', 'c2', 'c3'])
d1

c1  c2   c3
0   1  s1  0.1
1   2  s2  0.2
2   3  s3  0.3
3   4  s4  0.4
4   5  s5  0.5

In [15]:
a = np.array([10, 20, 30, 40, 50])
print(a.shape)
print(a[perm1])

(5,)
[30 10 50 40 20]


In [18]:
perm1 = np.random.permutation(5)
print(perm1)

[4 2 1 0 3]


In [19]:
d2 = d1.iloc[perm1]
print(d2)

   c1  c2   c3
4   5  s5  0.5
2   3  s3  0.3
1   2  s2  0.2
0   1  s1  0.1
3   4  s4  0.4


In [ ]:
import tensorflow as tf

inputs = tf.keras.Input(shape=(3,))
x = tf.keras.layers.Dense(4, activation=tf.nn.relu)(inputs)
outputs = tf.keras.layers.Dense(5, activation=tf.nn.softmax)(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

In [ ]:
out = model()

In [ ]:
import tensorflow as tf

inputs = tf.keras.Input(shape=(3,))
x = tf.keras.layers.Dense(4, activation=tf.nn.relu)(inputs)
outputs = tf.keras.layers.Dense(5, activation=tf.nn.softmax)(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

In [10]:
import numpy as np

In [ ]:
out = mode

In [13]:
model.compile()
out = model.fit(np.array([1, 2, 3]))

ValueError: in user code:

    File "c:\Users\samyj\miniconda3\envs\dmg_env\lib\site-packages\keras\engine\training.py", line 1284, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\samyj\miniconda3\envs\dmg_env\lib\site-packages\keras\engine\training.py", line 1268, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\samyj\miniconda3\envs\dmg_env\lib\site-packages\keras\engine\training.py", line 1249, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\samyj\miniconda3\envs\dmg_env\lib\site-packages\keras\engine\training.py", line 1050, in train_step
        y_pred = self(x, training=True)
    File "c:\Users\samyj\miniconda3\envs\dmg_env\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\samyj\miniconda3\envs\dmg_env\lib\site-packages\keras\engine\input_spec.py", line 253, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer 'model' (type Functional).
    
    Input 0 of layer "dense" is incompatible with the layer: expected min_ndim=2, found ndim=1. Full shape received: (None,)
    
    Call arguments received by layer 'model' (type Functional):
      • inputs=tf.Tensor(shape=(None,), dtype=int32)
      • training=True
      • mask=None


Yahoo Finance

In [2]:
import yfinance as yf
import numpy as np

In [3]:
lmat = yf.Ticker('LMAT')
print(lmat.info)

{'address1': '63 Second Avenue', 'city': 'Burlington', 'state': 'MA', 'zip': '01803', 'country': 'United States', 'phone': '781 221 2266', 'fax': '781 221 2223', 'website': 'https://www.lemaitre.com', 'industry': 'Medical Instruments & Supplies', 'sector': 'Healthcare', 'longBusinessSummary': "LeMaitre Vascular, Inc. designs, markets, sells, services, and supports medical devices and implants for the treatment of peripheral vascular disease worldwide. It offers restoreflow allografts; angioscope, a fiberoptic catheter used for viewing the lumen of a blood vessel; embolectomy catheters to remove blood clots from arteries or veins; thrombectomy catheters for removing thrombi in the venous system; occlusion catheters that temporarily occlude the blood flow; perfusion catheters to perfuse the blood and other fluids into the vasculature; and thrombectomy catheters, which features a silicone balloon for removing thrombi in the venous system. The company also provides artegraft biologic graft

In [5]:
hist = lmat.history(start="2015-02-25", end="2015-03-25")
hist

Open      High       Low     Close  Volume  \
Date                                                                        
2015-02-25 00:00:00-05:00  6.968150  7.179029  6.958982  7.096511    5300   
2015-02-26 00:00:00-05:00  7.334895  7.334895  6.894801  7.234040   23600   
2015-02-27 00:00:00-05:00  7.325727  7.334896  6.986488  6.986488   95000   
2015-03-02 00:00:00-05:00  7.169860  7.169860  6.931476  6.949813   19400   
2015-03-03 00:00:00-05:00  6.931476  7.215703  6.922308  7.169860   14000   
2015-03-04 00:00:00-05:00  7.234040  7.637460  7.114849  7.637460   98200   
2015-03-05 00:00:00-05:00  7.655798  7.655798  7.389908  7.545774   18700   
2015-03-06 00:00:00-05:00  7.573280  7.655798  7.426582  7.545774   11200   
2015-03-09 00:00:00-04:00  7.518269  7.646630  7.426583  7.619124   20300   
2015-03-10 00:00:00-04:00  7.655797  7.655797  7.399075  7.646628   52300   
2015-03-11 00:00:00-04:00  7.655798  7.655798  7.307390  7.344065   31400   
2015-03-12 00:00:00-04:00  7.600787  7.600787  7.316560  7.316560   16000   
2015-03-13 00:00:00-04:00  7.444918  7.545773  7.023162  7.142354   24700   
2015-03-16 00:00:00-04:00  7.151524  7.334896  7.105680  7.224873   29500   
2015-03-17 00:00:00-04:00  7.261546  7.353232  7.087342  7.334895   17500   
2015-03-18 00:00:00-04:00  7.408613  7.436257  7.288822  7.371754   13100   
2015-03-19 00:00:00-04:00  7.399398  7.648195  7.399398  7.620552   57300   
2015-03-20 00:00:00-04:00  7.592905  7.685053  7.417827  7.519188   29300   
2015-03-23 00:00:00-04:00  7.592906  7.592906  7.537618  7.565262   17500   
2015-03-24 00:00:00-04:00  7.694269  7.694269  7.574478  7.685054   31800   

                           Dividends  Stock Splits  
Date                                                
2015-02-25 00:00:00-05:00       0.00           0.0  
2015-02-26 00:00:00-05:00       0.00           0.0  
2015-02-27 00:00:00-05:00       0.00           0.0  
2015-03-02 00:00:00-05:00       0.00           0.0  
2015-03-03 00:00:00-05:00       0.00           0.0  
2015-03-04 00:00:00-05:00       0.00           0.0  
2015-03-05 00:00:00-05:00       0.00           0.0  
2015-03-06 00:00:00-05:00       0.00           0.0  
2015-03-09 00:00:00-04:00       0.00           0.0  
2015-03-10 00:00:00-04:00       0.00           0.0  
2015-03-11 00:00:00-04:00       0.00           0.0  
2015-03-12 00:00:00-04:00       0.00           0.0  
2015-03-13 00:00:00-04:00       0.00           0.0  
2015-03-16 00:00:00-04:00       0.00           0.0  
2015-03-17 00:00:00-04:00       0.00           0.0  
2015-03-18 00:00:00-04:00       0.04           0.0  
2015-03-19 00:00:00-04:00       0.00           0.0  
2015-03-20 00:00:00-04:00       0.00           0.0  
2015-03-23 00:00:00-04:00       0.00           0.0  
2015-03-24 00:00:00-04:00       0.00           0.0